name: Extract Inputs & Trigger Main Workflow

on:
  pull_request:
    types: [opened, edited]

jobs:
  extract-inputs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Debug PR Body
      run: |
        echo "PR Body:"
        cat $GITHUB_EVENT_PATH
        PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
        echo "$PR_BODY"

    - name: Extract Organization Username and Repository Name
      id: extract
      run: |
        PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
        echo "Extracted PR Body: $PR_BODY"
        ORG_USERNAME=$(echo "$PR_BODY" | grep -oP '(?<=- \*\*Org Name\*\*: \[).*?(?=\])' || echo "Not provided")
        REPO_NAME=$(echo "$PR_BODY" | grep -oP '(?<=- \*\*Repo Name\*\*: \[).*?(?=\])' || echo "Not provided")
        echo "Extracted Org Name: $ORG_USERNAME"
        echo "Extracted Repo Name: $REPO_NAME"
        echo "ORG_USERNAME=$ORG_USERNAME" >> $GITHUB_ENV
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

    - name: Display extracted inputs
      run: |
        echo "Org Name: ${{ env.ORG_USERNAME }}"
        echo "Repo Name: ${{ env.REPO_NAME }}"

    - name: Trigger main workflow
      run: |
        echo "Triggering workflow for Org: ${{ env.ORG_USERNAME }}, Repo: ${{ env.REPO_NAME }}"
        RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ env.ORG_USERNAME }}/${{ env.REPO_NAME }}/actions/workflows/Scenario_1.yml/dispatches \
        -d '{"ref":"main","inputs":{"organization":"${{ env.ORG_USERNAME }}","repository":"${{ env.REPO_NAME }}"}}')
        echo "HTTP Response Code: $RESPONSE"
        echo "Response Body:"
        cat response.txt
